# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('x', models.DecimalField(decimal_places=4, max_digits=50)),
                ('y', models.DecimalField(decimal_places=4, max_digits=50)),
                ('z', models.DecimalField(decimal_places=4, max_digits=50)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
