# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readings',
            name='y',
        ),
        migrations.RemoveField(
            model_name='readings',
            name='z',
        ),
        migrations.AlterField(
            model_name='readings',
            name='x',
            field=models.TextField(),
        ),
    ]
